### ISSUE TITLE
Finding the available moves

### ISSUE THREAD

**Issue by PeterffyZoltan** [Balint837/chess-pain#12]
- [x] static List FindKingLine => Find king with queen moves => returns whole diagonal/row/column, or whole board if not found (opposing* acts as partial* as well)
- [x] static List QueenEndpoints => Queen moves that don't go over friendlies
- [x] static List HorseMoves => Horse moves that don't capture friendlies ()
- [x] static List GetAttackers => Find enemy endpoints with queen moves that can attack current position
- [x] static Point GetAttacker => Finds the first enemy with queen moves that can attack current position
- [x] static List GetAttackersCount => Shorthand for MatrixCount(GetAttackers)
- [x] static List HasAttacker => Shorthand for MatrixAny(GetAttackers)
- [x] static List AvailablePieces => Returns matrix of available pieces
- [x] static Point FindKing => returns king position
- [ ] Shorthand for the above: Function(chessPiece)
- [x] abstract List GetMovesAll() => Moves of piece that are defined
- [x] virtual List GetMovesAvailable() => Moves of piece that don't go over friendlies (made abstract instead of virtual due to algorithmic problems)
- [x] virtual List GetMovesPinned()
- [x] Run MatrixAnd for each piece in GetAttackers on Attacker.GetMovesAll and FindKingLine.
- [x] If there is an instance where the result is equal to original FindKingLine, run MatrixAnd(Attacker.GetMovesAvailable, Piece.GetMovesAvailable)
- [x] virtual List GetMovesFinal() => if (HasAttacker(FindKing()) == false) then same as GetMovesPinned else if (MatrixCount(GetAttackers(FindKing())) > 1) then no moves else GetAttackers(FindKing())

**Comment by Balint837** [comment]
Shorthand: will not implement
